spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
      url: jdbc:postgresql://localhost:5432/spring
      username: fintech
      password: fintech1!
      driver-class-name: org.postgresql.Driver
debug: true